### ISSUE TITLE
[직업으로서의 소설가] 가장 마음에 드는 문장 최소 2개과 그 이유 고르기

### ISSUE THREAD

**Issue by agrajak** [Pigrabbit/book-club#11]
꼭 마음에 들었던 문장 뿐만이 아니라 이건 좀 공감하기 힘들었다. 하는 문장도 가능합니다. 같이 의견을 나누면 좋겠다! 하는 문장이면 다 가능합니다.

**Comment by Pigrabbit** [comment]
제 10회 누구를 위해서 쓰는가? 중
(p. 271) 

최소한의 지지자를 획득하는 것은 프로로서 필수 조건입니다. 하지만 그런 부분만 어느정도 해결할 수 있다면 
그다음은 *'나 자신이 즐길 수 있다', '나 자신이 납득할 수 있다'는 게 무엇보다 중요한 기준이 아닌가 하고 나는 생각합니다.*
즐겁지도 않은 일을 하면서 살아가는 인생이란 아무리 살아봤자 별로 즐겁지 않기 때문입니다.

**Comment by Pigrabbit** [comment]
제 4회 오리지낼리티에 대해서 중
(p.110)

만일 당신이 뭔가를 자유롭게 표현하기를 원한다면 '나는 무엇을 추구하는가'라는 것보다
오히려 *'뭔가를 추구하지 않는 나 자신은 원래 어떤 것인가'를, 그런 본모습을 머릿속에 그려보는게 좋을지도 모릅니다.*

**Comment by Pigrabbit** [comment]
제 7회 한없이 개인적이고 피지컬한 업 중
(p.197)

그런데 행운이란 말하자면 무료 입장권 같은 것입니다. 그런 점에서는 유전이나 금광과는 성격이 다릅니다.
(이하 중략)
입구에서 입장권을 건네고 행사장 안으로 들어갔다. *그다음에 어떤 행동을 취할지, 거기서 무엇을 발견하고 무엇을 취하고 혹은 버릴지,
거기서 생기게 될 몇 가지 장애물을 어떻게 뛰어넘을지, 그건 어디까지나 개인의 재능이나 자질이나 기량의 문제고,
인간으로서의 기량의 문제고, 세계관의 문제고, 또한 때로는 극히 심플하게 신체력의 문제입니다.*
어쨌든 그건 단순히 행운이라는 말만으로는 미처 다 처리되지 않는 사안입니다.

**Comment by 0407chan** [comment]
제 4회 오리지낼리티에 대해서 중
(p.113)
`신선하고, 에너지가 넘치고, 그리고 틀림없이 그 사람 자신의 것인 어떤 것`

**Comment by 0407chan** [comment]
제 3회 문학상에 대해서
(p.74)
새삼스럽게 말할 것도 없는 일이지만, 후세에 남는 것은 `작품`이지 `상`이 아닙니다.

(p.78)
나는 태어나서 지금까지 문학상의 심사위원을 맡을 일이 한번도 없습니다.
(중략)
왜냐하면, 이유는 간단한데, 나는 너무도 개인적인 인간이기 때문입니다. 
나라는 인간 속에는 나 자신의 고유한 비전이 있고, 거기에 형태를 부여해나가는 고유한 프로세스가 있습니다. 
그 프로세스를 유지하기 위해서는 포괄적인 삶의 방식에서부터 개인적이 되지 않을 수 없는 면이 있습니다.
그러지 않으면 제대로 글을 쓸 수 없는 것입니다.

**Comment by agrajak** [comment]
(p.134) 써야할 것이 아무것도 없다라는 지점에서 출발할 경우, 시동이 걸리기까지는 상당히 힘이 들지만 일단 바이클이 기동력을 얻어 앞으로 나아가기 시작하면 그 다음은 오히려 편해집니다... (중략) .. 당신이 소설을 쓰기로 마음먹었다면 주위를 주의 깊게 둘러보십시오 ... 세계는 따분하고 시시한 듯 보이면서도 실로 수많은 매력적이고 수수께끼 같은 원석이 가득합니다.

(p.57) 첫 소설을 쓸 때 느꼇던 문장을 만드는 일의 '기분 좋음', '즐거움'은 지금도 기본적으로 변함이 없습니다.
