### ISSUE TITLE
[이방인] 책 제목이 이방인인 이유? 

### ISSUE THREAD

**Issue by agrajak** [Pigrabbit/book-club#20]
책 제목이 왜 이방인인지에 대해서 이야기해보자.
이방인은 누굴 지칭하는 것일까?

**Comment by Pigrabbit** [comment]
원제 étranger
- 형용사: 외국의, 외부의, 국외자의, 낯선, 생소한, 무관한, 이물의
- 명사: 외국인, 외부 사람, 국외자
- *이방인*이라는 제목은 일본어 표현에서 온 것으로 보임

**Comment by Pigrabbit** [comment]
뫼르소가 이방인인것 같은데...
- 살인 후 재판장면
- 뫼르소의 평소 무관심한 태도
- 어머니 장례식 -> 슬픔에 대한 묘사가 없어...
- 읽으면서 독자로서 뫼르소와(주인공과) 가까워지는 느낌: 2부부터는 뫼르소에 공감, 동정.
