### ISSUE TITLE
[이방인] 뫼르소의 살인행위는 정당방위일까?

### ISSUE THREAD

**Issue by agrajak** [Pigrabbit/book-club#21]
또한 소설에서 '태양'을 통해 작가가 말하고 싶었던 내용은 무엇일까?

**Comment by Pigrabbit** [comment]
처음에는 재판에서 정당방위로 나올 것으로 예상
그러나 뫼르소의 법정에서의 태도가 유죄를 부름(거짓말 하지 않음, 적극적으로 변호하지 않음)

- '태양'의 의미는 무엇일까?
  - 장례식 행렬, 살인 장면
  - 사람이 피할 수 없는 것: 삶의 굴레
