### ISSUE TITLE
[이방인] 작중 뫼르소의 행동에 대해서 이야기 해보자.

### ISSUE THREAD

**Issue by agrajak** [Pigrabbit/book-club#22]
공감할 수 있던 부분과 이해하기 어려웠던 부분에 대해서 이야기 해보자.

**Comment by Pigrabbit** [comment]
어머니 장례식 때의 행동을 제외하면 이해가 된다. 
동정심이 느껴진다.

뫼르소 - 서민(특권층이나 고위층이 아님)
재판: 서민이 힘쓸 도리가 전혀 없다. 변호사도 국선변호사

뫼르소(주인공)의 운명이 타인(배심원)에 의해 결정된다.

<1부>
이해하기 어렵다
- 어머니 장례식 그리고 어머니의 죽음을 수용하는 태도.
- 언제 돌아가셨는지도 모르고 무관심한 태도.

공감된다
- 사람들(이웃들)과 어울리는 태도
  - 할아버지 강아지 찾아주기 위해 신경 써주는 부분
  - 레몽이 전 연인에 대해 갈등, 고민이 있었을 때 도와주려고 노력

<2부>
자기 스스로를 적극 변호하지 않는 태도
- 거짓말하지 않는다는 지조(또는 고집)를 지키는게 그렇게 중요한걸까

자신의 운명을 수동적으로 받아들이는 태도(예수 그리스도의 삶)

사형을 앞두고 교도소에서 사제에게 폭발하는 장면
