### ISSUE TITLE
[이방인] 뫼르소의 주변 인물에 대해서 이야기 해보자.

### ISSUE THREAD

**Issue by agrajak** [Pigrabbit/book-club#23]
- 살라마노 영감
- 레몽(레이몽)

**Comment by Pigrabbit** [comment]
살라마노 영감 - 개
- 애증의 관계
- 개가 있을 때는 동물학대
- 잃어버리고 개를 찾기 위해 노력. 길을 잃어서 잘못되지않을까 걱정.
- 괴팍해 보였었지만 인간적인 면모가 드러남.

레몽 - 레몽의 전 연인
- 애증의 관계
- 처음에는 정을 나누었지만, 나중에는 폭력으로 끝남

레몽
- 경찰서에서 조사받을 때, 뫼르소의 도움을 받음(증언을 해줌)
- 반대로 뫼르소 재판에서는 크게 관여 자체를 안했다.
- 적극적으로 나서서 구제하려고 노력하지 않았다.(부정적)

마리
- 의리가 있다. 진정성이 있다.
- 사형수가 되어서 집행날짜를 기다림에도 면회옴.
- 유일한 정상인으로 보임.

페드로 영감
- 어머니의 전남친(?)
- 이 인물의 상징하는 바는?
- 어머니가 양로원에서 새로운 시작
