### ISSUE TITLE
직업으로서의 소설가

### ISSUE THREAD

**Issue by agrajak** [Pigrabbit/book-club#6]
http://www.yes24.com/Product/Goods/25666436
![image](https://user-images.githubusercontent.com/16265376/103673548-0f5d7e80-4fc1-11eb-945b-39480aafd322.png)

- 하루키의 수필
- 옛날에 읽었던 책인데 다시 한번 읽어보고 싶다.
- 직업 의식에 관한 수필인데, 앞으로 개발자로 살아가면서 어떻게 살아가면 좋을지 좋은 힌트가 될 수 있지 않을까? 하는 생각이 들었습니다.

**Comment by Pigrabbit** [comment]
2월 도서 축 당첨
